NAME = philo

OBJ_DIR = obj
SRC_DIR = src
INC_DIR = inc

CC = gcc
CFLAGS = -Wall -Werror -Wextra -pthread -I$(INC_DIR)

SRCS = $(SRC_DIR)/main.c $(SRC_DIR)/utils.c $(SRC_DIR)/check_args.c $(SRC_DIR)/init.c \
	$(SRC_DIR)/routine.c
